services:
  app:
    build: .
    container_name: dah2026
    volumes:
      - .:/app
      - node-cache:/app/node_modules
      - angular-cache:/app/.angular
    ports:
      - "8100:8100"
      - "9876:9876"

  cypress:
    image: cypress/included:latest
    container_name: cypress_gui
    network_mode: "host"
    environment:
      - DISPLAY=$DISPLAY
      - XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR
      - ELECTRON_OZONE_PLATFORM_HINT=wayland
    volumes:
      - .:/app
      - node-cache:/app/node_modules
      - $XDG_RUNTIME_DIR/$WAYLAND_DISPLAY:$XDG_RUNTIME_DIR/$WAYLAND_DISPLAY
    working_dir: /app
    entrypoint: npx cypress open --project .

volumes:
  node-cache:
  angular-cache:
